[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "rust_dataframe_utils"
version = "0.1.0"
authors = ["Ditt Navn <din.email@eksempel.com>"]
description = "A Python module built with Rust and Polars"
readme = "README.md"
license = "MIT"