name: Rust and Python Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build Rust project
      run: cargo build --release

    - name: Run Rust tests
      run: cargo test

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install maturin
      run: pip install maturin

    - name: Build and install Rust module
      run: maturin develop

    - name: Install Python test dependencies
      run: pip install pytest

    - name: Run Python tests
      run: pytest test_rust_dataframe_utils.py