on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build Rust project
      run: cargo build --release

    - name: Run Rust tests
      run: cargo test

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        if [ -f ".venv/bin/activate" ]; then
          source .venv/bin/activate
        elif [ -f ".venv/Scripts/activate" ]; then
          .venv/Scripts/activate
        else
          echo "Virtual environment activation script not found."
          exit 1
        fi

    - name: Install maturin
      run: pip install maturin

    - name: Build and install Rust module
      run: maturin develop --bindings pyo3 --verbose

    - name: Verify installed packages
      run: pip list

    - name: Install Python test dependencies
      run: pip install pytest

    - name: Run Python tests
      run: |
        export PYTHONPATH=$(pwd):$PYTHONPATH
        pytest tests/
