name: Rust and Python Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest

    - name: Build and install Rust module
      run: python -m maturin develop

    - name: Run Rust tests
      run: cargo test

    - name: Run Python tests
      run: pytest test_rust_dataframe_utils.py